---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  generateName: snow-create-change-record-
  namespace: pacman
  labels:
    app.kubernetes.io/name: pacman
spec:
  tower_auth_secret: awx-tower-secret
  job_template_name: snow-create-change-record
  extra_vars:
    sn_severity: 2
    sn_priority: 2
