kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: tower
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#  storageClassName: gp2
  volumeMode: Filesystem

